version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=981514334627.dkr.ecr.us-east-1.amazonaws.com/myrepository_tsuji-k
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Scanning docker image...
      - curl -k -u $TL_USER:$parameter_store_env --output ./twistcli $TL_CONSOLE/api/v1/util/twistcli
      - chmod a+x ./twistcli
      - ./twistcli images scan --details -address $TL_CONSOLE -u $TL_USER -p $parameter_store_env --vulnerability-threshold critical --compliance-threshold critical $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...